### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by alemelis** [INSIGNEO/openBF#12]
- [ ] Heart model
- [x] Multiple inlets (#10)
- [ ] Bifurcation angle
- [ ] Bends
- [ ] Autoregulation
- [ ] Visco-elasticity
- [ ] Non-parabolic profile
- [ ] Annular flow loss coefficient

**Comment by ibenemerito88** [comment]
Copy config file in result folder

**Comment by fsmMLK** [comment]
allow choosing where the output directory will be, not only inside the input folder.

**Comment by ibenemerito88** [comment]
Convergence error: write vessel where maximum error is attained

E.g.
Conv. error = x% in vessel v

**Comment by ibenemerito88** [comment]
When creating result folder, check that a result folder with the same name does not already exist. If it does, delete it before creating a new one

**Comment by ibenemerito88** [comment]
Check vessels direction in conjunctions: if two vessels with different directions are joined, openBF will fail in solving the outlet

**Comment by ibenemerito88** [comment]
Output files:
Currently openBF saves .last even if the simulation has not converged after max_iteration. 
Save .last only if the simulation has converged. Save results to different format (neither last nor out) if it reaches max_iteration without converging.

**Comment by fsmMLK** [comment]
1-) (3+)-furcations (e.g: basilar+2xPCA+2xSCA)

**Comment by fsmMLK** [comment]
replacing 'Error norm > 100' by the actual value allows better convergency monitoring

**Comment by alemelis** [comment]
closing as there are now individual issues for all the above
