### ISSUE TITLE
Use docstrings

### ISSUE THREAD

**Issue by ChrisRackauckas** [INSIGNEO/openBF#14]
These kinds of comments

https://github.com/INSIGNEO/openBF/blob/master/src/bifurcations.jl#L17-L89

should probably be docstrings. Example:

```julia
"""
This docstring
"""
function f(x)
  x + 2
end
?f
```

These docstrings are the standard method for looking for function documentation and can be used by Documenter.jl to build documentation, so it's helpful to users if you use this method.

**Comment by alemelis** [comment]
You are perfectly right.

I'm actually in the process of [converting](https://github.com/INSIGNEO/openBF/blob/12055c7c2bbf23954af385308658637d54bdbe4c/src/boundary_conditions.jl#L17) everything to docstrings while I am also simplifying the code I/O and adding a more complete testing suite.

I've been using [jocco](https://github.com/lcw/jocco) for [documentation](https://insigneo.github.io/openBF/Docs/doc-files/openBF.html) so far, hence that kind of comments.
