### ISSUE TITLE
Use `Int` for machine integers instead of `Int64`

### ISSUE THREAD

**Issue by ChrisRackauckas** [INSIGNEO/openBF#15]
Right now there are a lot of functions which are restricted to 64-bit integers, even on 32-bit machines. This is likely why the 32-bit Windows tests fail on AppVeyor. However, note that the type assertions in the function signatures are only for function syntax anyways (and don't effect performance), so I would recommend just duck typing anyways.

**Comment by alemelis** [comment]
Hi @ChrisRackauckas, thanks for the tip on integers. I find helpful to state the types in the function signatures but I may overdoing it. My understanding was that a thorough type declaration would help in terms of performance, am I wrong? Thanks

**Comment by ChrisRackauckas** [comment]
They don't help for performance. Here's a post that describes it in some detail:

http://www.stochasticlifestyle.com/type-dispatch-design-post-object-oriented-programming-julia/

**Comment by alemelis** [comment]
all `Int64` changed to `Int` in v0.6.3 https://github.com/INSIGNEO/openBF/commit/1b1ce2a0f113f2b6f6d1d337ffced9ff1c51e783
