### ISSUE TITLE
Add entry in orda.shef.ac.uk (FigShare) to make citable

### ISSUE THREAD

**Issue by willfurnass** [INSIGNEO/openBF#17]
@alemelis The University of Sheffield Library (specifically @jezcope) would like to increase the number of software items in orda.shef.ac.uk (FigShare).  Would you want to create an entry for openBF?  If you don't have time I could do this on behalf if you let me know which version(s) it makes most sense to take snapshots of.

**Comment by alemelis** [comment]
Hi Will! the v0.6.3 was used for all our studies. However, the 0.7/1.0 in [`julia7`](https://github.com/INSIGNEO/openBF/tree/julia7) branch is the one compatible with the latest julia version. I didn't create the new version because I'm waiting for few dependencies to be fully compatible with latest julia. I'll have a look during the weekend and (possibly) I'll create the new version. This can be considered the stable one and can be linked to ORDA. Does it make sense?

**Comment by jezcope** [comment]
Hi @alemelis & @willfurnass, this would be great, thanks! You can upload code manually to ORDA if you want, but I should also make sure you're aware of the [github/figshare integration](https://knowledge.figshare.com/articles/item/how-to-connect-figshare-with-your-github-account-1) which makes it much easier. Indeed, if you like to tag your versions in github then you can have the ORDA record updated automatically when you release a new version. Old versions remain accessible and are flagged up with a link to the latest version.

Drop us a line at rdm@sheffeld.ac.uk with any questions.

**Comment by alemelis** [comment]
Hi @jezcope thanks for all the info.

I'm trying to set-up the GitHub/figshare integration but my university credentials are expired. Also, openBF is managed by the INSIGNEO group, so even if I create a new figshare account, I'm not able to manage this repo. @willfurnass can you do it for me? (perhaps @willgsheff can grant you access) I created a new release for Julia 1.0 compatibility (tested on our most recent benchmarks). If possible, I'd link both the v1.0 and the v0.6.3 as the latter was the most used in the past.

**Comment by willfurnass** [comment]
@jezcope When I try to 'import from GitHub' in FigShare I see my personal public repos but not those in the @INSIGNEO GH Organisation - know if FigShare supports importing from GH orgs?  NB I'm one of the owners of the INSIGNEO GH Org.

**Comment by willfurnass** [comment]
Created doi:10.15131/shef.data.7166183 for v.0.6.3.  Published in FigShare but not accessible by FigShare search yet.  

Uploaded a tarball that was generated using:

```sh
git archive --format tar.gz --output  openbf-git-archive-v0.6.3.tar.gz -9 v0.6.3
```

and added links both the repo and docs in the FigShare item description.

**Comment by willfurnass** [comment]
@alemelis: @jezcope has emailed us re this but not sure if your UoS email is still active; let me know if not.

**Comment by alemelis** [comment]
@jezcope @willfurnass 
got the email, thanks! :smiley:

**Comment by jezcope** [comment]
We generally recommend using the DOI to link to wherever possible. For this one that's:

- https://doi.org/10.15131/shef.data.7166183.v1 ← always resolves to this specific version
- https://doi.org/10.15131/shef.data.7166183 ← always resolves to the latest version in ORDA

**Comment by jezcope** [comment]
PS. Thanks to both of you for getting this sorted!

**Comment by alemelis** [comment]
@willfurnass @jezcope thank you so much, it looks great!

I'll update the readme with the right links and close this issues asap
